# Generated by Django 3.0.5 on 2020-05-01 23:22

import dataentry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demodata',
            name='email',
            field=models.EmailField(default=dataentry.models.email_default, max_length=500),
        ),
        migrations.AddField(
            model_name='demodata',
            name='firstname',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='demodata',
            name='lastname',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
